// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqb3HV3FodmGc78h4imiF339BF1CorPx8',
    appId: '1:717878215483:web:132534ba44f694cbd9ed1e',
    messagingSenderId: '717878215483',
    projectId: 'fir-b9e95',
    authDomain: 'fir-b9e95.firebaseapp.com',
    databaseURL: 'https://fir-b9e95-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b9e95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-DCke-LhXavjGus1CpmOX8Ve9YiLg28',
    appId: '1:717878215483:android:5e9ff617bae71aa9d9ed1e',
    messagingSenderId: '717878215483',
    projectId: 'fir-b9e95',
    databaseURL: 'https://fir-b9e95-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b9e95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rfnG50syD8kPOJnxWcyjdr4OvnE2m6M',
    appId: '1:717878215483:ios:7390d02f7eae1027d9ed1e',
    messagingSenderId: '717878215483',
    projectId: 'fir-b9e95',
    databaseURL: 'https://fir-b9e95-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b9e95.appspot.com',
    androidClientId: '717878215483-d4jjafk5bh0d0tjqpaoatco6llgheb13.apps.googleusercontent.com',
    iosClientId: '717878215483-543e3e3p2jj1p0g7b233ndk9t3cpjt5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1rfnG50syD8kPOJnxWcyjdr4OvnE2m6M',
    appId: '1:717878215483:ios:7390d02f7eae1027d9ed1e',
    messagingSenderId: '717878215483',
    projectId: 'fir-b9e95',
    databaseURL: 'https://fir-b9e95-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b9e95.appspot.com',
    androidClientId: '717878215483-d4jjafk5bh0d0tjqpaoatco6llgheb13.apps.googleusercontent.com',
    iosClientId: '717878215483-543e3e3p2jj1p0g7b233ndk9t3cpjt5f.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqb3HV3FodmGc78h4imiF339BF1CorPx8',
    appId: '1:717878215483:web:d4ef8b46409d7d97d9ed1e',
    messagingSenderId: '717878215483',
    projectId: 'fir-b9e95',
    authDomain: 'fir-b9e95.firebaseapp.com',
    databaseURL: 'https://fir-b9e95-default-rtdb.firebaseio.com',
    storageBucket: 'fir-b9e95.appspot.com',
  );

}